Tools/PC/Jenkins_reconnect.sh
To save time to install alloem image that can trigger via Jenkins again, we can set up the DUT by following steps for further testing if the image is installed by USB key or installed by Stock Ubuntu image locally.
Jira Card: https://warthogs.atlassian.net/browse/CQT-1740
=> Add: script for reconnecting DUT to Jenkins

Tools/PC/oem-qa-checkbox-installer/README.md, Tools/PC/oem-qa-checkbox-installer/bin/boxer.py, Tools/PC/oem-qa-checkbox-installer/bin/env-setup.sh, Tools/PC/oem-qa-checkbox-installer/bin/get-hw-info.sh, Tools/PC/oem-qa-checkbox-installer/bin/get-id-info.py, Tools/PC/oem-qa-checkbox-installer/bin/install-packages.sh, Tools/PC/oem-qa-checkbox-installer/conf/plainbox.conf, Tools/PC/oem-qa-checkbox-installer/conf/setting.conf, Tools/PC/oem-qa-checkbox-installer/oem-qa-checkbox-installer.sh
This is a tool to help us setup test environment and download checkbox.
The main purpose for this PR is to **migrate oem-qa-installer** to here and also fix some small bugs. If there are some bug won't affect this script, I will fix it in the future PR.
1. Migrate all files related to oem-qa-checkbox-installer to here.
2. Split the big old main script into several small python and shell script, so we could easily maintain it in the future.
3. Add wpa3 to `plainbox.conf`.
4. Adjust the path to config file in `boxer.py`.
5. Add `Remove setting.conf` at the end of script because it contains personal info.
6. Add `Install openssh-server` to ssh to DUT.
Refactor boxer.py cause it is a little bit outdated, and some parameters are not even using.
=> Migrate oem-qa-checkbox-installer

Tools/PC/oem-qa-checkbox-installer/bin/boxer.py
Update class name to fit the pep8 naming convention.
class tcolor
class Tcolor
=> Fix: class naming style in pep8

Tools/PC/oem-qa-checkbox-installer/conf/plainbox.conf
Since CQT-2031 has merged into checkbox and released  in 2.6, we could change the default palinbox.conf of oem-qa-tools to multiple MAC in one BTDEVADDR style.
=> Change to multiple MAC in one BTDEVADDR

Tools/PC/oem-qa-checkbox-installer/README.md, Tools/PC/oem-qa-checkbox-installer/bin/boxer.py, Tools/PC/oem-qa-checkbox-installer/conf/setting.conf
According to the instructions from cert team, QA team members should use `testing` repository for regular testing.
=> Set default repository to "testing"

Tools/PC/oem-qa-checkbox-installer/bin/autologin.sh, Tools/PC/oem-qa-checkbox-installer/bin/env-setup.sh, Tools/PC/oem-qa-checkbox-installer/conf/checkbox-testing-env-dconf
Add to set current user to autologin and change to use dconf load to set testing environment to make it easier to restore.
While installation, it will dump all dconf configuration to `env-for-restore-dconf` and could be restored by `dconf load / < env-for-restore-dconf`
=> Add to set current user to autologin while oem checkbox installation.

tox.ini
The pyYAML 5.4.1 is too old for python 3.10+, therefore we have to upgrade it to 6.0.1
=> Upgrade pyYAML to 6.0.1 for python 3.10+

Tools/PC/transfer-hw-to-cert/README.md, Tools/PC/transfer-hw-to-cert/handlers/cert_team_google_sheet_handler.py, Tools/PC/transfer-hw-to-cert/handlers/cqt_handler.py, Tools/PC/transfer-hw-to-cert/handlers/hic_handler.py, Tools/PC/transfer-hw-to-cert/handlers/telops_handler.py, Tools/PC/transfer-hw-to-cert/main.py, Tools/PC/transfer-hw-to-cert/tests/test_cqt_handler.py, Tools/PC/transfer-hw-to-cert/tests/test_data/jira_card_handler_data.py
Enhance the description details to Jira TELOPS DUT Send To Cert card from the CQT hardware transfer card. Additionally, update the reporter of the TELOPS card to match the assignee of CQT card.
https://warthogs.atlassian.net/browse/CQT-3130 
1. Copy the CQT content to TELOPS card.
2. Remove ''qa_launchpad_id''.
3. Modify: if the CID has already exist in the google_sheet, it will not raise the exception.
4. Bypass if the HIC connection is down.
=> Update TELOPS DUT Send To Cert card sourced from the CQT card

Tools/PC/testflinger_yaml_generator/template/shell_scripts/00_initial
Add the shellcheck ignore to avoid the test command can't be ran as correct in testflinger.
=> Fix the conflict between shellcheck and testflinger

API/Jira/apis/base.py, Tools/PC/transfer-hw-to-cert/configs/jira_telops.json, Tools/PC/transfer-hw-to-cert/handlers/telops_handler.py
**Summary**
Improving the Jira card for TELOPS status based on its creation from a CQT Jira card enables cert team members identifying the card's classification.
**Test Result:**
From Cert team request https://warthogs.atlassian.net/browse/CQT-3501.
Need to change the status while creating the TELOPS card with "To Do: QA Lab" status from CQT board.
The "To Do: QA Lab" transition id on TELOPS board is "2", the details can be found in the CQT-3501.
=> Update Jira TELOPS DUT Send To Cert card with QA LAB status

Tools/PC/transfer-hw-to-cert/handlers/telops_handler.py
Trail run the test that didn't meet the issue, but running on Jenkins which is causing the key error.
Log:
Created the following cards to TELOPS board successfully
Traceback (most recent call last):
File "/root/oem-qa-tools/transfer-hw-to-cert/main.py", line 113, in <module>
main()
File "/root/oem-qa-tools/transfer-hw-to-cert/main.py", line 85, in main
create_send_dut_to_cert_card_in_telops(
File "/root/oem-qa-tools/transfer-hw-to-cert/handlers/telops_handler.py", line 67, in create_send_dut_to_cert_card_in_telops
transition_id = telops_jira_api.jira_project['transition_data'][
KeyError: 'transition_data'
Build step 'Execute shell' marked build as failure
=> Fix the #42 hw transfer to cert team which is causing the key error

API/Jira/configs/jira_config/project.json, API/Jira/scenarios/pc/pc.py, Tools/PC/transfer-hw-to-cert/handlers/cqt_handler.py
Follow the new company-owned board with associated name for fields. Adjust the column names in current applications accordingly.
Test Result:
https://warthogs.atlassian.net/browse/TELOPS-817
https://warthogs.atlassian.net/browse/TELOPS-818
=> Update the jira card field name by incorporating the new board.

Tools/PC/oem-qa-checkbox-installer/bin/install-packages.sh
sosreport will failed the test `snappy/test-snaps-confinement`
besides, we have packaged sosreport in bugit, there is no need to install it separately by default
=> remove sosreport installing from oem-qa-checkbox-installer

Tools/PC/oem-qa-checkbox-installer/oem-qa-checkbox-installer.sh
Run this script with root will change the autologin user to root and login failed after reboot.
Therefore, check the current user isn't root at beginning to avoid this error.
=> Avoid running `oem-qa-checkbox-installer.sh` as root

Tools/PC/transfer-hw-to-cert/handlers/cert_team_google_sheet_handler.py, Tools/PC/transfer-hw-to-cert/tests/test_utils_common.py, Tools/PC/transfer-hw-to-cert/utils/common.py
Add shelf, frame and partition number for valid location by
following structure specified in the Cert team's google sheet. 
Fix the error that exclude the rack location in parsing locations.
Issue:
https://github.com/canonical/oem-qa-tools/issues/61
https://github.com/canonical/oem-qa-tools/issues/62
Test Result:
https://warthogs.atlassian.net/browse/OEMQA-3824
=> Fix: #61 #62 add valid number in the new lab6 and fix rack locations errors

Tools/PC/QA_banner.sh
There are more and more DUTs under testing at the same time and make it hard to know which DUT could be used for debugging by SWE and HWE. Therefore, OEMQA would like to add this QA_banner to notice someone who would like to use that DUT is under testing or not.
=> Add the function to add and remove QA_banner

API/C3/apis/base.py, Tools/PC/transfer-hw-to-cert/handlers/c3_handler.py, Tools/PC/transfer-hw-to-cert/handlers/cqt_handler.py, Tools/PC/transfer-hw-to-cert/main.py, Tools/PC/transfer-hw-to-cert/tests/test_cqt_handler.py, Tools/PC/transfer-hw-to-cert/tests/test_data/jira_card_handler_data.py
Add return process in HW transfer tools.
The commit introduces the return process in the HW transfer tools,
1. separate the content and test result, making it more flexible to use.
2. allowing automatic changes to the C3 status when DUTs are no longer necessary,
such as the SI or DVT1 phases.
This automation streamlines the workflow and ensures accurate status updates.
Test: https://warthogs.atlassian.net/browse/OQS-3309
=> DUT remove return process

Tools/PC/testflinger_yaml_generator/template/shell_scripts/02_Install_checkbox_deb, Tools/PC/testflinger_yaml_generator/template/shell_scripts/02_Install_checkbox_snap, Tools/PC/testflinger_yaml_generator/template/shell_scripts/15_install_checkbox_on_agent, Tools/PC/testflinger_yaml_generator/template/shell_scripts/90_start_test
**Changes:**
1. Added plainbox-provider-pc-sanity in templates to be installed on DUT. This provider is now hosted on [checkbox beta](https://launchpad.net/~checkbox-dev/+archive/ubuntu/beta), so no need to install pc sanity ppa
2. Added template to install checkbox-ng on agent, then switch to specific version to match with DUT. This code was copied from Cert team Jenkins and adjusted to agent env.
3. Use "control" instead of "remote"
**Test:**
- Run shellcheck against new templates
- Run [infrastructure-checkbox-run-debug](http://10.131.60.220:8080/job/infrastructure-checkbox-run-debug/102/) job, which clones this repo and generates the job.yaml (Note: there are some errors when switching checkbox version, but the same errors are found in cert teams SRU job. So I assume those are not …
=> Add plainbox-provider-pc-sanity and install checkbox on agent

Tools/PC/testflinger_yaml_generator/testflinger_yaml_generator.py
Expand tf-yaml-generator to support [oem_autoinstall device connector](https://github.com/canonical/testflinger/pull/304) in 24.04.
It adds 3 more parameters + attachments in the provision stage of job.yaml. These parameters are optional, so if args not added, then no changes to original behavior and templates.
Sample provisioning data for 24.04:
```
job_queue: artur-oemscript-2404
provision_data:
url: http://10.131.60.220:8080/job/somerville-noble-oem-24.04a/lastSuccessfulBuild/artifact/out/somerville-noble-oem-24.04a-20240806-59.iso
token_file: "jenkins-token.txt"
user_data: "ubuntu-oem-image-builder/alloem-init/cloud-configs/redeploy/user-data"
authorized_keys: "ubuntu-oem-image-builder/injections/alloem-init/chroot/minimal.standard.live.hotfix.squashfs/etc/ssh/authorized_keys" …
```
=> testflinger-yaml-generator: add provision parameters for oem_autoinstall connector

Tools/PC/testflinger_yaml_generator/template/launcher_config/main.conf, Tools/PC/testflinger_yaml_generator/template/shell_scripts/90_start_test, Tools/PC/testflinger_yaml_generator/testflinger_yaml_generator.py
Change the submitting checkbox submission way.
make the submit return stored in the `artifacts/submission_url.log`
The original way is using the checkbox auto submission mechanism, and we are hard to get the submission url unless we parser the testflinger output. It will take a long time to get the testflinger output via `testflinger results <UUID>`.
The new way is using the testflinger to help us submit checkbox submission, put the submission_url in a file, and we can download the artifacts via `testflinger artifacts <uuid>`.
Once we need the submission url, we only need to parse the `artifacts/submission_url.log`.
Testflinger UUID: [2cb37d6b-9e8d-4d40-8a8d-b73ecd514096](https://testflinger.canonical.com/jobs/2cb37d6b-9e8d-4d40-8a8d-b73ecd514096) to check the test command field and …
=> TFG: change method of submiting checkbox submission

Tools/PC/testflinger_yaml_generator/testflinger_yaml_generator.py
Add --provisionOnly flag (Default=False) to generate job.yaml without default test_data stage.
Use case if when need to only provision the DUT without test plan.
**Test:**
Provision only:
`./testflinger_yaml_generator.py -c 202405-33980 -o prov-new.yaml --provisionType url --provisionImage http://10.131.60.220:8080/job/somerville-noble-oem-24.04a/lastSuccessfulBuild/artifact/out/somerville-noble-oem-24.04a-20240820-71.iso --provisionToken ~/testflinger/test-yaml/jenkins-token.txt --provisionAuthKeys ~/testflinger/test-yaml/authorized_keys --provisionUserData ~/testflinger/test-yaml/user-data --provisionOnly`
Test default plan only without provision:
`./testflinger_yaml_generator.py -c 202405-33980 -o prov-new.yaml`
Provision and test default plan:
`./testflinger_yaml_generator.py -c …
=> tf-generator: Remove test_data in job.yaml when --testplan is not provided

Tools/PC/transfer-hw-to-cert/handlers/c3_v2_handler.py
The C3 API is migrating to V2 and there are some functions are not supported in V1 right now. Therefore, this PR is going to add a script that use V2 API in the back-end to do it and the `main.py` will be changed to use this script while it stable.
=> use the c3 v2 api to do hardware transfer to cert lab

Tools/PC/transfer-hw-to-cert/handlers/c3_v2_handler.py
This follows up the change of C3 and limit the datacentre to TEL-L4 and TEL-L10 to make C3 to response faster.
=> migrate hostdata to labresource

Tools/env-setup/checkbox-server-install.sh
Due to the fact that the jobs in [ptp4l](https://github.com/canonical/checkbox/blob/5ebfbaf1c254fcd2616e76ac6f3850eaccf42df9/contrib/checkbox-ce-oem/checkbox-provider-ce-oem/units/ptp/jobs.pxu) require ptp4l to be set up, we need to add this into the server setup script.
=> Add ptp4l server setup

Tools/PC/oem-qa-checkbox-installer/oem-qa-checkbox-installer.sh
checkbox remote couldn't support to define configuration file.
Therefore, copy plainbox.conf to checkbox.conf to prevent missing ssid etc.
=> Copy plainbox.conf to checkbox.conf

Tools/PC/testflinger_yaml_generator/template/shell_scripts/00_initial
Some kernel version will be marked as security update that will force kernel to be updated during test period. Therefore, add related setting to avoid this.
=> avoid kernel be updated during test period

API/Jira/scenarios/pc/pc.py
Jira API failed to search jira issue with patterns with hyphen character this issue is not fixed yet in Jira API, so applied an workaround for this issue https://jira.atlassian.com/browse/JRACLOUD-75866
=> workaround - fixed search patterns for jira summary

Tools/PC/testflinger_yaml_generator/template/shell_scripts/15_install_checkbox_on_agent
Installing with sudo caused problem with leftover files on agent. Consecutive job run will fail.
Using pipx works on cert lab and hot lab DUTs.
Test by generating the file locally and submit several times
`./testflinger_yaml_generator.py -c 202401-33392 --testplan audio-automated -o audio.yaml`
Jobs completed: 
https://testflinger.canonical.com/jobs/f63ce908-3f6f-4539-97dc-7d443ee5c6a1
https://testflinger.canonical.com/jobs/456c20b8-d8b4-4471-b544-ec7fe32f31bf
=> 15_install_checkbox_on_agent: Install with pipx and remove dir afterwards

.github/workflows/markdown_and_shellcheck.yml, .github/workflows/test-jira-card-creator.yml, .github/workflows/test-transfer-hw-to-cert.yml, .github/workflows/tox.yml, tox.ini
20.04 runners are getting deprecated by github. This PR updates all the github runner yamls to start using >=22.04 runners and testing python code on >=py3.10.
=> Update github runners to at least 22.04 and remove <py3.10 testing environments

Tools/PC/c3-submission-helpers/README.md, Tools/PC/c3-submission-helpers/parse-suspend-30-logs.py, Tools/PC/c3-submission-helpers/summarize-reboot-check-test.py
basically the newest (not very tested) versions of the helper scripts in https://github.com/canonical/oem-qa-tools/tree/main/Tools/PC/c3-submission-helpers
If you encounter issues with the scripts on the main branch (for example if they are not filtering certain outputs correctly), try these ones
requires python 3.10+, no dependencies
(if you are not seeing bold error messages, it might be because your terminal font can't be bold-ed.)
=> Edge stress test parser scripts

Tools/PC/persist_journal.py
This script edits journalctl's config file to make it 
- save up to 200 entries
- use up to 10G of space
- prefer disk storage
It will restart the daemon for you so all you need to do is `sudo python3 persist_journal.py` on the DUT.
To save more entries change the values here:
```py
journal_config["Journal"]["SystemMaxFiles"] = "200"
journal_config["Journal"]["SystemMaxUse"] = "10G"
```
To make the files live longer, uncomment this line:
```py
journal_config["Journal"]["MaxFileSec"] = "180day"
```
=> Simple script to ask journalctl to save more journal entries

Tools/PC/testflinger_yaml_generator/template/launcher_config/main.conf
Below message is popped up:
Config: daemon section name is deprecated. Use agent instead. Connecting to 10.102.180.115:18871. Timeout: 600s
=> fix: update deprecated daemon section

Tools/PC/testflinger_yaml_generator/template/shell_scripts/15_install_checkbox_on_agent
Update the pipx command when installing checkbox, because --spec flag no longer supported.
The same change is already in cert scriptlets:
https://github.com/canonical/certification-lab-ci-tools/blob/afadf13478120ee1bcc459b94f9352061e5d4051/scriptlets/install_checkbox_agent_source#L47C1-L48C66
After fix:
```
+ echo 'Installing checkbox in agent container'
Installing checkbox in agent container
++ _run checkbox-cli --version
++ ssh -t -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@10.102.180.146 checkbox-cli --version
+ CHECKBOX_VERSION=$'6.0.0.dev37\r'
+ git clone --depth=1 https://github.com/canonical/hwcert-jenkins-tools.git
Cloning into 'hwcert-jenkins-tools'...
+ git clone --filter=tree:0 https://github.com/canonical/checkbox.git
Cloning into 'checkbox'...
Updating …
```
=> change: Remove --spec from pipx because it's not supported
