canonical/oem-qa-tools

- .gitignore
- API/Jira/.gitignore
- API/Jira/README.md
- API/Jira/apis/base.py
- API/Jira/configs/jira_config/project.json
- API/Jira/scenarios/pc/README.md
- API/Jira/scenarios/pc/configs/somerville.json
- API/Jira/scenarios/pc/configs/stella.json
- API/Jira/scenarios/pc/configs/sutton.json
- API/Jira/scenarios/pc/pc.py
- API/Jira/tests/__init__.py
- API/Jira/tests/dev_create_pc_tasks.py
- API/Jira/tests/test_base_api.py
- API/Jira/tests/testing_data.json
- API/Jira/utils/logging_utils.py
In this commit, I did the following things.
- Migrate the whole Jira API business logic
- Refactor a small peice of code of base.py and restructure the project
- Add unit test for base.py
- Refactor the PC scenario for better maintaince
- Add unit test for PC scenario
- Complete the README files
> Migrate jira

- Tools/stressor-test/README.md
- Tools/stressor-test/capture-stressor.py
- Tools/stressor-test/stress-ng-stressor-test.sh
Adding a stress-ng stress test scripts to run stress-ng stress test directly
> Add: stress-ng stress tests with stress-ng snap

- API/Jira/README.md
- API/Jira/scenarios/pc/README.md
Update the Readme files and add __init__.py in scenario directory.
> Update Jira API service

- .github/workflows/shellcheck.yml
- .github/workflows/tox.yml
- Tools/PC/Jenkins_reconnect.sh
- Tools/PC/jira-card-creator/pc_platform_tracker.py
- Tools/PC/jira-card-creator/setup.sh
- Tools/PC/jira-card-creator/tests/test_create_qa_jira_card.py
- Tools/PC/oem-qa-checkbox-installer/bin/boxer.py
- Tools/PC/oem-qa-checkbox-installer/bin/get-id-info.py
- tox.ini
1. Add github  action to scan code by flake8 and shellcheck.
2. I have changed some code, but I haven't checked everything will work as usual. If I changed your code and shows some error behaviors, please kindly let me know to fix it.
> Add: code quality check in github action

- API/Jira/apis/base.py
- API/Jira/scenarios/pc/pc.py
- Tools/PC/jira-card-creator/pc_platform_tracker.py
- Tools/PC/oem-qa-checkbox-installer/bin/boxer.py
- tox.ini
Following the discussion in sprint, adding the pep8 naming check in github action. If any naming changed in the PR wouldn't fit the original meaning, please let me know.
> Add pep8 naming check for python script

- .github/workflows/markdown.yml
- API/C3/README.md
- API/GoogleSheet/README.md
- API/Jira/README.md
- API/Jira/scenarios/pc/README.md
- README.md
- Tools/PC/jira-card-creator/README.md
- Tools/PC/oem-qa-checkbox-installer/README.md
- Tools/stressor-test/README.md
Use markdownlint-cli2 to check Markdown content by github action, and fix errors that be found by markdownlint-cli2.
> Add markdown linter

- Tools/PC/jira-card-creator/create_qa_jira_card.py
- Tools/PC/jira-card-creator/pc_platform_tracker.py
- Tools/PC/jira-card-creator/tests/test_create_qa_jira_card.py
correct the contents for the stell PRTS records
> Fix: correct the contents for stella PRTS records

- Tools/PC/merge_test_matrix/README.md
- Tools/PC/merge_test_matrix/merge_test_matrix.py
This script could be used to automate the process of generating test matrix from initial test results. It helps QA to have the test scope for projects.
Jira card: https://warthogs.atlassian.net/browse/CQT-2849
> Add merge_test_matrix script to generate a test matrix file

- API/Jira/scenarios/pc/pc.py
fix #27 
somehow jira JQL search does not work with the specific keyword "stella-winterice"
which leads to repeatedly creating the same card every day
When checking the story card under project stella
let the JQL search check both lp_tag and platform_tag
You can find the jellyfish-jaiko (platform tag for stella-winterice) won't be created again 
```
INFO  - pc        : create_task_card 1113 - ==================== Project: Stella ====================
INFO  - pc        : _load_project_profile 83   - Loading "stella" profile...
INFO  - pc        : create_card 804  - --------------------prts--------------------
INFO  - pc        : create_card 804  - --------------------rts--------------------
INFO  - pc        : _rts_handler 764  - Creating the task of "fossa-graveler"
INFO  - pc        : …
```
> fix: check both lp_tag and platform_tag when creating card for stella

- Tools/PC/jira-card-creator/pc_platform_tracker.py
Modified Sutton project book mapping since some of the date contexts were changed.
> Modifiy sutton project book mapping

- API/Jira/apis/base.py
- API/Jira/scenarios/pc/pc.py
> Fix some bugs for applying OEMQA board

- Tools/PC/transfer-hw-to-cert/configs/google_sheet_link.json
Add new TEL-L6 to tables in google_sheet_link.json
Jira Card:https://warthogs.atlassian.net/browse/OEMQA-3829
> Add new TEL-L6 to tables in google_sheet_link.json

- Tools/PC/merge_test_matrix/merge_test_matrix.py
Initial Tes Jira cardt:https://warthogs.atlassian.net/browse/OEMQA-3881 
Modify merge_test_matrix Jira card: https://warthogs.atlassian.net/browse/OEMQA-3887
> Add panel resolution value in merge_test_matrix script.

- Tools/PC/oem-qa-checkbox-installer/conf/plainbox.conf
- Add WWAN config in `./conf/plainbox.conf`.
- Add the description to show how to get the `WWAN_CONTROL_IF`, `WWAN_NET_IF`
> Add WWAN config

- Tools/PC/transfer-hw-to-cert/handlers/c3_v2_handler.py
This is going to update the holder, location and status while processing the hardware transfer task.
> add updating holder, location and status while hardware transfering

- Tools/PC/transfer-hw-to-cert/main.py
- Tools/PC/transfer-hw-to-cert/utils/common.py
1. Add more valid lab number for the extending of lab.
2. Google sheet is deprecated. Removing related feature.
3. HIC is deprecated. Removing related feature.
Tested in the qa-transfer-hw-to-cert-lab-c3-base-staging jenkins job
> Add lab 1, 2, 7, 8, 9 into valid location

- Tools/env-setup/checkbox-server-install.sh
- Tools/env-setup/wol_server.py
Add the Wake-on-LAN server script here and make it could be installed by checkbox-server-install.sh
> add Wake-on-Lan server script 

- Tools/PC/transfer-hw-to-cert/configs/jira_telops.json
- Tools/PC/transfer-hw-to-cert/handlers/telops_handler.py
Update title and TO DO Cert Lab Jira Card in TELOPS board while QA running the HW transfer process.
https://warthogs.atlassian.net/browse/OEMQA-5899
> Update title and TO DO Cert Lab Jira Card in TELOPS board

- Tools/PC/testflinger_yaml_generator/template/shell_scripts/15_install_checkbox_on_agent
This adds pipx, it's dependency (python3-env), and other tools on agent.
Related to previous merge:https://github.com/canonical/oem-qa-tools/pull/96
Tests:
https://testflinger.canonical.com/jobs/cefcb642-7c72-408d-8024-5713eb0c88ea
> testflinger_yaml_generator: apt install pipx and other tools on agent

- .github/workflows/checkbox_manifest_github_page.yaml
a github action to create a github page to help user to create manifest.json for checkbox.
Example github page:
https://hanhsuan.github.io/ci-testing/
> Checkbox manifest helper

- .github/workflows/checkbox_manifest_github_page.yaml
Change to use self host runner
> change to use self host runner

- .github/workflows/checkbox_manifest_github_page.yaml
The full_manifest.json and auto_manifest.json are missing in the previous PR.
> fix missing command

- Tools/env-setup/bugit_helper.sh
1. migrate from sku to canonical_id
2. migrate from bugit v1 to bugit v2
> Migrate API and bugit command
